-- db/052_feats_factions_category.sql
--
-- A seventh feat category, 'factions', and the five faction feats moved into
-- it. The ask was "a button labelled Factions that finds these five".
--
-- WHY A CATEGORY AND NOT A TAG. feats.tags already exists and would need no
-- migration at all, which makes it the obvious answer and the wrong one:
--
--   * The filter row on the Feats page is generated by mapping featCategories.
--     A seventh value in that tuple IS the button -- no new state, no second
--     filter axis beside categoryFilter, no JSX. A tag needs all three.
--   * useSearchBar matches on name and customName and nothing else, so tagging
--     these five 'factions' would not make the word "factions" find them in the
--     search box either. The tag would be invisible from both directions.
--   * featsByCategory groups the character sheet's feat list, so the sheet gets
--     a "Factions" header out of the same change, and CreateFeat's category
--     <select> gets the option. A tag gets none of that without more code.
--
-- THE COST, STATED PLAINLY: category is exclusive, so Harpers stops being
-- 'social' and Zhentarim stops being 'skill'. That is a real loss of one bit
-- per feat and it is accepted here because the bit was arbitrary -- the five
-- landed in four different categories (two in 'combat') for no reason anyone
-- would be able to reconstruct, since what they actually have in common is
-- being faction memberships. If per-feat flavour on top of the faction ever
-- matters, that is what tags are for, and they are still empty.
--
-- PLURAL, DELIBERATELY. featCategoryLabel title-cases the stored value and
-- nothing else, so 'factions' is what renders the button as "Factions". The
-- other six read as adjectives ('combat' feat, 'social' feat) and are singular
-- for that reason; this one names a set. Not a typo -- do not "fix" it to
-- 'faction' without also changing the label the ask asked for.
--
-- NO UPDATE POLICY NEEDED, AND THIS IS NOT A PRECEDENT FOR ONE. 039 ships
-- SELECT and INSERT only, so nothing in the client can change a feat's
-- category. This file does not care: run in the SQL editor it executes as the
-- table owner, outside RLS entirely. A DM editing their own homebrew from the
-- browser is a separate piece of work and still undone.
--
-- THE CAMPAIGN IS NAMED ONCE, in c_name, per 051. The five feat names likewise
-- appear once, in c_feats. 051's failure was a literal repeated across
-- statements until one copy drifted; the shape of this file is that lesson
-- applied, not a coincidence.
--
-- NOTE THE APOSTROPHE IN "Lords' Alliance": U+2019, a curly right single quote
-- (hex e28099), not an ASCII '. That is how the row was actually written and it
-- is reproduced exactly below. Retype it with a straight quote and the array
-- matches four rows, not five -- which the assertion catches rather than
-- letting it commit half-done.
--
-- IDEMPOTENT. The constraint is dropped if present before being recreated, the
-- update is a no-op once the rows already read 'factions', and the assertion
-- describes the end state rather than the rows touched. The ledger insert still
-- refuses the second run first, per 036.
--
-- AFTERWARDS: add "factions" to featCategories in src/services/feats.ts, before
-- 'general', which its own comment reserves as the leftovers and therefore
-- last. parseOneOf narrows the text column against that tuple at the boundary,
-- so until the tuple knows the word, every one of these five rows throws on the
-- way into the client instead of rendering. The migration and that one line go
-- together; neither is correct alone. (Done in the same commit as this file.)
--
-- NO `notify pgrst` AND NO gen:types, unlike 039's footer. Both of those exist
-- to tell the client about new tables, columns and functions; this file adds no
-- schema object, only a wider check on a column that already exists. The
-- generated type for feats.category is plain `string` and stays that way -- the
-- seven values live in the tuple, not in database.types.ts, which is exactly
-- why the tuple edit above is not optional.
--
-- RUN THE MIGRATION BLOCK BELOW ON ITS OWN, then the verification blocks one at
-- a time.


-- ===========================================================================
-- MIGRATION
-- ===========================================================================
--
-- CORRECT OUTPUT: "Success. No rows returned."

begin;

-- Widened before the update, for the obvious reason. Dropped by name rather
-- than by `alter ... add constraint if not exists`, which Postgres does not
-- have: drop-and-recreate is the whole idiom for editing a check.
alter table public.feats drop constraint if exists feats_category_check;

alter table public.feats add constraint feats_category_check
  check (category in (
    'combat', 'defense', 'magic', 'skill', 'social', 'general', 'factions'
  ));

do $$
declare
  -- The one place this campaign is named.
  c_name constant text := 'Not Curse of Strahd';

  -- The one place these feats are named. The curly apostrophe is load-bearing;
  -- see the header.
  c_feats constant text[] := array[
    'Emerald Enclave',
    'Harpers',
    'Lords’ Alliance',
    'Order of the Gauntlet',
    'Zhentarim'
  ];

  v_campaign uuid;
  v_moved    int;
  v_final    int;
begin
  select id into strict v_campaign
  from public.campaigns
  where name = c_name;

  -- Scoped to the campaign as well as the names, so a shared catalogue row or
  -- another campaign's homebrew that happens to share a name is untouched. The
  -- five are homebrew, so campaign_id is theirs and is not null.
  update public.feats
     set category = 'factions'
   where campaign_id = v_campaign
     and name = any(c_feats)
     and category is distinct from 'factions';

  get diagnostics v_moved = row_count;
  raise notice 'Moved % feat(s) into factions.', v_moved;

  -- ---- Assert the end state, not the work. --------------------------------
  --
  -- 051's lesson, and the reason v_moved above is a notice and this is not: a
  -- second run legitimately moves zero rows, so "rows touched" cannot be the
  -- check. What must be true when this file is finished is that all five of
  -- these feats exist in this campaign and read 'factions' -- which fails
  -- loudly on a mistyped name and on a feat that was never created.
  select count(*) into v_final
  from public.feats
  where campaign_id = v_campaign
    and name = any(c_feats)
    and category = 'factions';

  if v_final <> array_length(c_feats, 1) then
    raise exception
      'Expected % faction feats in campaign "%", found %. Rolled back -- check the names in c_feats against the campaign''s actual rows; note that "Lords’ Alliance" uses a curly apostrophe (U+2019), not an ASCII one.',
      array_length(c_feats, 1), c_name, v_final;
  end if;
exception
  when no_data_found then
    raise exception
      'No campaign is named "%". Run: select id, name from campaigns order by name; then correct c_name -- it is the only occurrence.',
      c_name;
  when too_many_rows then
    raise exception
      'More than one campaign is named "%". Name is not unique -- replace the c_name lookup with the campaign''s uuid.',
      c_name;
end
$$;

insert into public.schema_migrations (version) values ('052');

commit;


-- ===========================================================================
-- VERIFICATION -- run one block at a time. The SQL editor renders only the last
-- result set of a run, so pasting all three shows BLOCK 2 and silently discards
-- the rest. No ledger rows; each block ends in rollback.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- BLOCK 0: the constraint admits the new value and still refuses a wrong one
-- ---------------------------------------------------------------------------
--
-- 039's BLOCK 1 pattern -- the refusal is caught and reported as a row rather
-- than allowed to abort, so a pass is not painted red by the editor.
--
-- Singular 'faction' is the plausible wrong answer rather than a nonsense
-- string: it is the value someone reaches for having read the button label and
-- guessed at the column behind it.
--
-- CORRECT OUTPUT: one row, factions_admitted = t and singular_outcome =
--                 'rejected by the check (23514)'. 'INSERT SUCCEEDED' in the
--                 second means the recreated constraint is missing or too wide.

begin;

insert into public.feats (name, category, description)
values ('Constraint Probe', 'factions', 'Rolled back.');

do $$
begin
  insert into public.feats (name, category, description)
  values ('Bad Category', 'faction', 'Should not exist.');
  perform set_config('verification.outcome', 'INSERT SUCCEEDED -- CONSTRAINT TOO WIDE', true);
exception
  when check_violation then
    perform set_config('verification.outcome', 'rejected by the check (23514)', true);
end
$$;

select 'block 0: the widened check' as check,
       jsonb_build_object(
         'factions_admitted',
           (select count(*) = 1 from public.feats where name = 'Constraint Probe'),
         'singular_outcome', current_setting('verification.outcome')
       ) as result;

rollback;


-- ---------------------------------------------------------------------------
-- BLOCK 1: the campaign's roster, so the move is visible in context
-- ---------------------------------------------------------------------------
--
-- CORRECT OUTPUT: the five faction feats, all category 'factions', plus
-- whatever else this campaign has authored. Fewer than five in 'factions'
-- means a name in c_feats did not match -- but the assertion above would have
-- rolled the file back, so fewer here means the migration never ran.

begin;
  select f.name, f.category, f.tags
  from feats f
  join campaigns c on c.id = f.campaign_id
  where c.name = 'Not Curse of Strahd'
  order by f.category, f.name;
rollback;


-- ---------------------------------------------------------------------------
-- BLOCK 2: nothing outside this campaign moved
-- ---------------------------------------------------------------------------
--
-- The shared 2014 catalogue is campaign_id null and 040 never wrote a faction,
-- so a 'factions' row with a null campaign_id would mean the update's campaign
-- scope failed open.
--
-- CORRECT OUTPUT: zero rows.

begin;
  select id, name, category
  from feats
  where category = 'factions'
    and campaign_id is null;
rollback;
